# PolyVault Configuration Settings
# Modify these values to customize port bindings and file storage locations.

server.port=8080
socket.port=5050
data.directory=data
storage.directory=data/storage
metadata.directory=data/metadata

# Firebase Configuration (Required for Hybrid Auth Verification)
firebase.api.key=AIzaSyAObvOnvicvdHZkWmyXoWaunrLT5gzvEwI
firebase.project.id=polyvault-6990a

